name: hello world
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      #This step checks out a copy of the repo.
      - name: Hello world checkout
        uses: actions/checkout@v4

      - name: Group of log lines
        run: |
          echo "::group::Hello Worlds"
          echo "Hello World 1"
          echo "::endgroup::"