on:
  workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      #This step checks out a copy of the repo.
      - name: Hello world checkout
        uses: actions/checkout@v4
      #This step references the diretory containing the action.
      - name: Use local hello-world action
        uses: ./.github/actions/hello-world-action
      - name: Group of log lines
        run: |
          echo "::group::Hello Worlds"
          echo "Hello World 1"
          echo "::endgroup::"